<?
class Uri{
//	const abs_host = 'esjr.nl';
//	const abs_www = 'www.esjr.nl';
//	const abs_admin = 'admin.esjr.nl';
//	const abs_media = 'media.esjr.nl';
//	const www = 'http://www.esjr.nl/';
//	const admin = 'http://admin.esjr.nl/';
//	const media = 'http://media.esjr.nl/';
	const abs_host = 'localhost';
	const abs_www = 'localhost';
	const abs_admin = 'localhost/admin';
	const abs_media = 'localhost/media';
	const www = 'http://localhost/world/';
	const admin = 'http://localhost/admin/';
	const media = 'http://localhost/media/';
	const data = '/data/';
	const admin_data = '/data/admin/'; 
	const environment_data = '/data/environment/'; 
	const world_data = '/data/world/'; 
	const admin_css = '/data/admin/css/'; 
	const admin_img = '/data/admin/img/'; 
	const admin_js = '/data/admin/js/'; 
	const admin_services = '/data/admin/services/'; 
	const textimages = 'http://media.esjr.nl/textimages/'; 
	const pageimages = 'http://media.esjr.nl/pageimages/'; 
	const errorpage = '/data/environment/errorpage/'; 
	const content_css = '/data/world/css/edit.css'; 
	const css = '/data/world/css/'; 
	const img = '/data/world/img/'; 
	const js = '/data/world/js/'; 
	const world_services = '/data/world/services/'; 
	const blueprint = '/data/world/services/blueprint-lvdg-1/'; 
	const prototype = '/data/world/services/bundle-prototype-1.6.1.js'; 
	const scriptaculous = '/data/world/services/bundle-scriptaculous-1.8.1.js'; 
	const lightbox = '/data/world/services/lightbox-lvdg/'; 
	const calendar = 'http://www.esjr.nl/agenda/'; 
	const blog = 'http://www.esjr.nl/columns/'; 
	const workgroups = 'http://www.esjr.nl/werkgroepen/'; 


	public static $constants = array (
  'abs_host' => self::abs_host,
  'abs_www' => self::abs_www,
  'abs_admin' => self::abs_admin,
  'abs_media' => self::abs_media,
  'www' => self::www,
  'admin' => self::admin,
  'media' => self::media,
  'data' => '/data/',
  'admin_data' => '/data/admin/',
  'environment_data' => '/data/environment/',
  'world_data' => '/data/world/',
  'admin_css' => '/data/admin/css/',
  'admin_img' => '/data/admin/img/',
  'admin_js' => '/data/admin/js/',
  'admin_services' => '/data/admin/services/',
  'textimages' => 'http://media.esjr.nl/textimages/',
  'pageimages' => 'http://media.esjr.nl/pageimages/',
  'errorpage' => '/data/environment/errorpage/',
  'content_css' => '/data/world/css/edit.css',
  'css' => '/data/world/css/',
  'img' => '/data/world/img/',
  'js' => '/data/world/js/',
  'world_services' => '/data/world/services/',
  'blueprint' => '/data/world/services/blueprint-lvdg-1/',
  'prototype' => '/data/world/services/bundle-prototype-1.6.1.js',
  'scriptaculous' => '/data/world/services/bundle-scriptaculous-1.8.1.js',
  'lightbox' => '/data/world/services/lightbox-lvdg/',
  'calendar' => 'http://www.esjr.nl/agenda/',
  'blog' => 'http://www.esjr.nl/columns/',
  'workgroups' => 'http://www.esjr.nl/werkgroepen/',
);}

